version: '2'
services:
  pgsql:
    container_name: set_db_10
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - set-db-data:/var/lib/postgresql/data/pgdata
  odoo:
    container_name: set_odoo_12
    image: odoo:12
    depends_on:
      - pgsql
    ports:
      - "$port:8069"
      - "$chat_port:8072"
    volumes:
      - set-web-data:/var/lib/odoo
      - ./docker:/etc/odoo/
      - ./addons:/mnt/extra-addons
volumes:
  set-web-data:
  set-db-data: